import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import getConfig from "next/config";

import styles from "../styles/Home.module.css";

export const getServerSideProps: GetServerSideProps = async (...data) => {
  const { serverRuntimeConfig } = getConfig();

  console.log(data);

  const tracer = serverRuntimeConfig.tracer.init();

  tracer.use("next", {
    service: "telemetry-demo",
  });

  return new Promise(() => ({
    tracing: true,
  }));
};

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Test</p>
      </main>
    </div>
  );
};

export default Test;
