import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Tracer from "dd-trace";

import styles from "../styles/Home.module.css";

export const getServerSideProps: GetServerSideProps = async ({
  query = "",
  resolvedUrl = "",
  locale = "",
  req: { rawHeaders, method },
}) => {
  return Tracer.trace("page.request", { resource: "test" }, async () => ({
    props: {
      query,
      resolvedUrl,
      locale,
      rawHeaders,
      method,
    },
  }));
};

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Test</p>
      </main>
    </div>
  );
};

export default Test;
